global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mcp'
    static_configs:
      - targets: ['mcp-app:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']